name: Update leaderboard hourly

on:
  schedule:
    - cron: '0 * * * *'   # каждый час (UTC)
  workflow_dispatch:       # запуск вручную из вкладки Actions

permissions:
  contents: write          # нужен доступ на коммит/пуш

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # (опционально) если используешь кастомный домен — держим файл CNAME
      # Создай Repo Variable (Settings → Variables) с именем CUSTOM_DOMAIN и значением своего домена.
      - name: Ensure CNAME (optional)
        if: ${{ vars.CUSTOM_DOMAIN != '' }}
        run: echo "${{ vars.CUSTOM_DOMAIN }}" > CNAME

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      # --- SSH-туннель — запускаем ТОЛЬКО если USE_SSH=true ---
      - name: Start SSH tunnel (if needed)
        if: ${{ secrets.USE_SSH == 'true' }}
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DB_INTERNAL_HOST: ${{ secrets.DB_INTERNAL_HOST }}
          DB_INTERNAL_PORT: ${{ secrets.DB_INTERNAL_PORT }}
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa
          # Пробрасываем локальный порт 5433 на внутренний адрес БД через бастион
          nohup ssh -o StrictHostKeyChecking=no -i id_rsa -N \
            -L 5433:${DB_INTERNAL_HOST}:${DB_INTERNAL_PORT} \
            ${SSH_USER}@${SSH_HOST} -p ${SSH_PORT} &
          # даём туннелю подняться
          sleep 4

      - name: Run export.py
        env:
          # Значения для прямого подключения (если USE_SSH != true)
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          USE_SSH: ${{ secrets.USE_SSH }}
        run: |
          # Если задействован SSH-туннель — подключаемся к нему
          if [ "${USE_SSH}" = "true" ]; then
            export DB_HOST=127.0.0.1
            export DB_PORT=5433
          fi
          python export.py

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add leaderboard.csv CNAME || true
          git diff --cached --quiet || git commit -m "update leaderboard"
          git push
